# bidirectional_lstm
# CUDA_VISIBLE_DEVICES=0 nohup python train.py --max_features 20000 --maxlen 100 --embedding_dims 128 --dropout 0.5 --model_name bidirectional_lstm --batch_size 128  --lstm_output_size 64 --nb_epoch 100 > ./logs/bidirectional_lstm &
# CUDA_VISIBLE_DEVICES=0 nohup python train.py --max_features 200000 --maxlen 100 --embedding_dims 300 --dropout 0.5 --model_name bidirectional_lstm --batch_size 128  --lstm_output_size 64 --nb_epoch 100 --embedding_file /home/hegx/Research/Quora_Question_Pairs/data/glove.840B.300d.txt --train_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/train/ --test_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/test/ > ./logs/bidirectional_lstm1 &
# CUDA_VISIBLE_DEVICES=0 nohup python train.py --max_features 200000 --maxlen 400 --embedding_dims 300 --dropout 0.5 --model_name bidirectional_lstm --batch_size 128  --lstm_output_size 64 --nb_epoch 100 --embedding_file /home/hegx/Research/Quora_Question_Pairs/data/glove.840B.300d.txt --train_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/train/ --test_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/test/ > ./logs/bidirectional_lstm2 &

# cnn_lstm
# CUDA_VISIBLE_DEVICES=0 nohup python train.py --max_features 20000 --maxlen 100 --embedding_dims 128 --dropout 0.25 --model_name cnn_lstm --batch_size 128 --nb_filter 64 --filter_length 5 --nb_epoch 100 --pool_length 4 --lstm_output_size 70 > ./logs/cnn_lstm &
# CUDA_VISIBLE_DEVICES=1 nohup python train.py --max_features 200000 --maxlen 100 --embedding_dims 300 --dropout 0.25 --model_name cnn_lstm --batch_size 128 --nb_filter 64 --filter_length 5 --nb_epoch 100 --pool_length 4 --lstm_output_size 70 --embedding_file /home/hegx/Research/Quora_Question_Pairs/data/glove.840B.300d.txt --train_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/train/ --test_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/test/ > ./logs/cnn_lstm1 &
# CUDA_VISIBLE_DEVICES=0 nohup python train.py --max_features 200000 --maxlen 400 --embedding_dims 300 --dropout 0.25 --model_name cnn_lstm --batch_size 128 --nb_filter 64 --filter_length 5 --nb_epoch 100 --pool_length 4 --lstm_output_size 70 --embedding_file /home/hegx/Research/Quora_Question_Pairs/data/glove.840B.300d.txt --train_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/train/ --test_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/test/ > ./logs/cnn_lstm2 &

# cnn
# CUDA_VISIBLE_DEVICES=0 nohup python train.py --max_features 5000 --maxlen 400 --embedding_dims 50 --dropout 0.2 --model_name cnn --batch_size 128 --nb_filter 250 --filter_length 3 --nb_epoch 100 --hidden_dims 250 > ./logs/cnn &
# CUDA_VISIBLE_DEVICES=1 nohup python train.py --max_features 200000 --maxlen 400 --embedding_dims 300 --dropout 0.2 --model_name cnn --batch_size 128 --nb_filter 250 --filter_length 3 --nb_epoch 100 --hidden_dims 250 --embedding_file /home/hegx/Research/Quora_Question_Pairs/data/glove.840B.300d.txt --train_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/train/ --test_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/test/ > ./logs/cnn1 &

# lstm
# CUDA_VISIBLE_DEVICES=0 nohup python train.py --max_features 20000 --maxlen 80 --embedding_dims 128 --dropout 0.2 --model_name lstm --batch_size 128 --nb_epoch 100 --lstm_output_size 128 > ./logs/lstm &
# CUDA_VISIBLE_DEVICES=0 nohup python train.py --max_features 200000 --maxlen 80 --embedding_dims 300 --dropout 0.2 --model_name lstm --batch_size 128 --nb_epoch 100 --lstm_output_size 128 --embedding_file /home/hegx/Research/Quora_Question_Pairs/data/glove.840B.300d.txt --train_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/train/ --test_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/test/ > ./logs/lstm1 &
# CUDA_VISIBLE_DEVICES=0 nohup python train.py --max_features 200000 --maxlen 400 --embedding_dims 300 --dropout 0.2 --model_name lstm --batch_size 128 --nb_epoch 100 --lstm_output_size 128 --embedding_file /home/hegx/Research/Quora_Question_Pairs/data/glove.840B.300d.txt --train_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/train/ --test_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/test/ > ./logs/lstm2 &
# CUDA_VISIBLE_DEVICES=1 nohup python train.py --max_features 200000 --maxlen 400 --embedding_dims 300 --dropout 0.2 --model_name lstm --batch_size 128 --nb_epoch 100 --lstm_output_size 300 --embedding_file /home/hegx/Research/Quora_Question_Pairs/data/glove.840B.300d.txt --train_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/train/ --test_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/test/ > ./logs/lstm3 &

# cnn_based_rnn
# CUDA_VISIBLE_DEVICES=0 nohup python train.py --max_features 20000 --maxlen 1000 --embedding_dims 300 --dropout 0.5 --model_name cnn_based_rnn --batch_size 50 --nb_filter 128 --filter_length 3 --nb_epoch 100 --hidden_dims 300 --lstm_output_size 300 > ./logs/cnn_based_rnn &
# CUDA_VISIBLE_DEVICES=0 nohup python train.py --max_features 200000 --maxlen 400 --embedding_dims 300 --dropout 0.5 --model_name cnn_based_rnn --batch_size 50 --nb_filter 250 --filter_length 3 --nb_epoch 100 --hidden_dims 300 --lstm_output_size 300 --embedding_file /home/hegx/Research/Quora_Question_Pairs/data/glove.840B.300d.txt --train_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/train/ --test_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/test/ > ./logs/cnn_based_rnn0 &
# CUDA_VISIBLE_DEVICES=0 nohup python train.py --max_features 200000 --maxlen 1000 --embedding_dims 300 --dropout 0.5 --model_name cnn_based_rnn --batch_size 50 --nb_filter 250 --filter_length 3 --nb_epoch 100 --hidden_dims 300 --lstm_output_size 300 --embedding_file /home/hegx/Research/Quora_Question_Pairs/data/glove.840B.300d.txt --train_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/train/ --test_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/test/ > ./logs/cnn_based_rnn2 &
# CUDA_VISIBLE_DEVICES=1 nohup python train.py --max_features 200000 --maxlen 400 --embedding_dims 300 --dropout 0.5 --model_name cnn_based_rnn --batch_size 50 --nb_filter 250 --filter_length 4 --nb_epoch 100 --hidden_dims 300 --lstm_output_size 300 --embedding_file /home/hegx/Research/Quora_Question_Pairs/data/glove.840B.300d.txt --train_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/train/ --test_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/test/ > ./logs/cnn_based_rnn3 &
# CUDA_VISIBLE_DEVICES=1 nohup python train.py --max_features 200000 --maxlen 400 --embedding_dims 300 --dropout 0.5 --model_name cnn_based_rnn --batch_size 50 --nb_filter 300 --filter_length 2 --nb_epoch 100 --hidden_dims 300 --lstm_output_size 300 --embedding_file /home/hegx/Research/Quora_Question_Pairs/data/glove.840B.300d.txt --train_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/train/ --test_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/test/ > ./logs/cnn_based_rnn4 &
# CUDA_VISIBLE_DEVICES=0 nohup python train.py --max_features 200000 --maxlen 400 --embedding_dims 300 --dropout 0.5 --model_name cnn_based_rnn --batch_size 50 --nb_filter 250 --filter_length 3 --nb_epoch 100 --hidden_dims 300 --lstm_output_size 600 --embedding_file /home/hegx/Research/Quora_Question_Pairs/data/glove.840B.300d.txt --train_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/train/ --test_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/test/ > ./logs/cnn_based_rnn2 &

# complex_cnn_based_rnn
# CUDA_VISIBLE_DEVICES=1 nohup python train.py --max_features 200000 --maxlen 400 --embedding_dims 300 --dropout 0.5 --model_name complex_cnn_based_rnn --batch_size 50 --nb_filter 250 --filter_length 3 --nb_epoch 100 --hidden_dims 300 --lstm_output_size 300 --embedding_file /home/hegx/Research/Quora_Question_Pairs/data/glove.840B.300d.txt --train_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/train/ --test_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/test/ > ./logs/complex_cnn_based_rnn &

# cnn_inner_rnn
# CUDA_VISIBLE_DEVICES=1 nohup python train.py --max_features 200000 --maxlen 400 --embedding_dims 300 --dropout 0.5 --model_name cnn_inner_rnn --batch_size 50 --nb_filter 250 --filter_length 3 --nb_epoch 100 --hidden_dims 300 --lstm_output_size 300 --embedding_file /home/hegx/Research/Quora_Question_Pairs/data/glove.840B.300d.txt --train_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/train/ --test_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/test/ > ./logs/cnn_inner_rnn &
# CUDA_VISIBLE_DEVICES=1 nohup python train.py --max_features 200000 --maxlen 400 --embedding_dims 300 --dropout 0.5 --model_name cnn_inner_rnn --batch_size 50 --nb_filter 250 --filter_length 3 --nb_epoch 100 --hidden_dims 300 --lstm_output_size 300 --embedding_file /home/hegx/Research/Quora_Question_Pairs/data/glove.840B.300d.txt --train_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/train/ --test_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/test/ > ./logs/cnn_inner_rnn1 &

# rnn_inner_rnn
# CUDA_VISIBLE_DEVICES=0 nohup python train.py --max_features 200000 --maxlen 400 --embedding_dims 300 --dropout 0.5 --model_name rnn_inner_rnn --batch_size 50 --nb_filter 250 --filter_length 3 --nb_epoch 100 --hidden_dims 300 --lstm_output_size 300 --embedding_file /home/hegx/Research/Quora_Question_Pairs/data/glove.840B.300d.txt --train_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/train/ --test_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/test/ > ./logs/rnn_inner_rnn &

# rnn_cat_rnn
# CUDA_VISIBLE_DEVICES=1 nohup python train.py --max_features 200000 --maxlen 400 --embedding_dims 300 --dropout 0.5 --model_name rnn_cat_rnn --batch_size 50 --nb_filter 250 --filter_length 3 --nb_epoch 100 --hidden_dims 300 --lstm_output_size 300 --embedding_file /home/hegx/Research/Quora_Question_Pairs/data/glove.840B.300d.txt --train_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/train/ --test_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/test/ > ./logs/rnn_mul_rnn_cat &

# pre_attention_inner_rnn
# CUDA_VISIBLE_DEVICES=0 nohup python train.py --max_features 200000 --maxlen 400 --embedding_dims 300 --dropout 0.5 --model_name pre_attention_inner_rnn --batch_size 50 --nb_filter 250 --filter_length 3 --nb_epoch 100 --hidden_dims 300 --lstm_output_size 300 --embedding_file /home/hegx/Research/Quora_Question_Pairs/data/glove.840B.300d.txt --train_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/train/ --test_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/test/ > ./logs/pre_attention_inner_rnn1 &
CUDA_VISIBLE_DEVICES=1 nohup python train.py --max_features 200000 --maxlen 400 --embedding_dims 300 --dropout 0.5 --model_name pre_attention_inner_rnn --batch_size 50 --nb_filter 250 --filter_length 3 --nb_epoch 100 --hidden_dims 300 --lstm_output_size 300 --embedding_file /home/hegx/Research/Quora_Question_Pairs/data/glove.840B.300d.txt --train_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/train/ --test_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/test/ > ./logs/pre_attention_inner_rnn2 &
# CUDA_VISIBLE_DEVICES=0 python train.py --max_features 200000 --maxlen 400 --embedding_dims 300 --dropout 0.5 --model_name pre_attention_inner_rnn --batch_size 50 --nb_filter 250 --filter_length 3 --nb_epoch 100 --hidden_dims 300 --lstm_output_size 300 --embedding_file /home/hegx/Research/Quora_Question_Pairs/data/glove.840B.300d.txt --train_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/train/ --test_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/test/

# cnn_add_rnn
# CUDA_VISIBLE_DEVICES=1 nohup python train.py --max_features 200000 --maxlen 400 --embedding_dims 300 --dropout 0.5 --model_name cnn_add_rnn --batch_size 50 --nb_filter 250 --filter_length 3 --nb_epoch 100 --hidden_dims 300 --lstm_output_size 300 --embedding_file /home/hegx/Research/Quora_Question_Pairs/data/glove.840B.300d.txt --train_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/train/ --test_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/test/ > ./logs/cnn_add_rnn &

# CUDA_VISIBLE_DEVICES=0 python train.py --max_features 200000 --maxlen 1000 --embedding_dims 300 --dropout 0.5 --model_name cnn_based_rnn --batch_size 50 --nb_filter 128 --filter_length 3 --nb_epoch 100 --hidden_dims 300 --lstm_output_size 300 --embedding_file /home/hegx/Research/Quora_Question_Pairs/data/glove.840B.300d.txt --train_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/train/ --test_path /home/hegx/Research/TextClassification/imdb/data/aclImdb/test/

# CUDA_VISIBLE_DEVICES=0 nohup python train.py --max_features 20000 --maxlen 80 --embedding_dims 128 --dropout 0.2 --model_name model --batch_size 128 --nb_filter 64 --filter_length 5 --nb_epoch 10 --pool_length 4 --lstm_output_size 70 > ./logs/lstm &
